name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_and_push_docker_image:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Generate date
      id: date
      run: |
        echo "::set-output name=date::$(date +'%y%m%d')"

    - name: Create config.yml
      run: |
        echo "${{ secrets.CONFIG_YML }}" > ./backend/config.yml

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19

    - name: Generate Swagger documentation
      run: |
        cd backend
        go run github.com/swaggo/swag/cmd/swag@latest init

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Registry
      uses: docker/login-action@v1
      with:
        registry: joosum.kr.ncr.ntruss.com
        username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
        password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./backend
        file: ./backend/Dockerfile
        platforms: linux/amd64
        tags: joosum.kr.ncr.ntruss.com/joosum-backend:${{ steps.date.outputs.date }}
        push: true

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push_docker_image
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Generate date
      id: date
      run: |
        echo "::set-output name=date::$(date +'%y%m%d')"

    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VM_HOST_IP }}
        username: root
        password: ${{ secrets.VM_PASSWORD }}
        script: |
          docker pull joosum.kr.ncr.ntruss.com/joosum-backend:${{ steps.date.outputs.date }}
          docker stop $(docker ps -q -f 'expose=5001')
          docker run --rm -d -v /etc/ssl/certs:/etc/ssl/certs -p 5001:5001 \
            --log-opt max-size=10k --log-opt max-file=3 \
            --name server joosum.kr.ncr.ntruss.com/joosum-backend:${{ steps.date.outputs.date }} -env=prod
